import { useState } from "react";
import { useAuth } from "@/contexts/AuthContext";
import { useLanguage } from "@/contexts/LanguageContext";
import { supabase } from "@/integrations/supabase/client";
import { useToast } from "@/hooks/use-toast";
import { motion } from "framer-motion";
import { GraduationCap, Loader2, Sparkles, Send } from "lucide-react";
import HistoryDrawer from "@/components/history/HistoryDrawer";
import CourseViewer, { type CourseData } from "@/components/course/CourseViewer";
import { useNavigate } from "react-router-dom";

const CoursesPage = () => {
  const { user, profile } = useAuth();
  const { t, lang } = useLanguage();
  const { toast } = useToast();
  const navigate = useNavigate();
  const [prompt, setPrompt] = useState("");
  const [course, setCourse] = useState<CourseData | null>(null);
  const [loading, setLoading] = useState(false);
  const [generatedTitle, setGeneratedTitle] = useState("");

  const examplePrompts = [
    t("Teach me JavaScript from scratch", "আমাকে শূন্য থেকে JavaScript শেখাও"),
    t("Class 10 Physics - Light chapter in detail", "দশম শ্রেণি পদার্থবিজ্ঞান - আলো অধ্যায় বিস্তারিত"),
    t("Complete SSC Mathematics course", "সম্পূর্ণ SSC গণিত কোর্স"),
    t("HSC Chemistry Organic part", "HSC রসায়ন জৈব অংশ"),
    t("Digital Marketing basics", "ডিজিটাল মার্কেটিং বেসিক"),
  ];

  const handleGenerate = async () => {
    if (!user) {
      toast({
        title: t("Sign up required", "সাইন আপ প্রয়োজন"),
        description: t("Please sign up first to generate AI courses", "AI কোর্স তৈরি করতে আগে সাইন আপ করুন"),
        variant: "destructive",
      });
      navigate("/auth");
      return;
    }

    if (!prompt.trim()) {
      toast({ title: t("Error", "ত্রুটি"), description: t("Write what you want to learn", "কী শিখতে চাও লেখো"), variant: "destructive" });
      return;
    }
    setLoading(true);
    setCourse(null);
    setGeneratedTitle(prompt);

    try {
      const { data, error } = await supabase.functions.invoke("generate-course", {
        body: {
          classLevel: profile?.class_level || "9",
          subjectName: prompt,
          board: profile?.board || "Dhaka",
          language: lang,
        },
      });
      if (error) throw error;
      if (data?.error) throw new Error(data.error);

      // Handle both new format (course object) and legacy format (chapters array)
      if (data?.course?.course_overview) {
        setCourse(data.course);
      } else if (data?.chapters && Array.isArray(data.chapters)) {
        // Legacy format - convert to new structure
        setCourse(null);
        toast({ title: t("Outdated cache", "পুরাতন ক্যাশ"), description: t("Regenerating with new format...", "নতুন ফরম্যাটে পুনরায় তৈরি হচ্ছে...") });
      } else {
        throw new Error("Invalid response format");
      }
    } catch (error: any) {
      toast({ title: t("Error", "ত্রুটি"), description: error.message, variant: "destructive" });
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="p-4 md:p-6 space-y-6 max-w-4xl mx-auto">
      <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="flex items-start justify-between">
        <div>
          <div className="flex items-center gap-3 mb-2">
            <GraduationCap className="w-8 h-8 text-primary" />
            <h1 className="text-2xl md:text-3xl font-bold text-foreground">
              {t("AI Course Generator", "AI কোর্স জেনারেটর")}
            </h1>
          </div>
          <p className="text-muted-foreground text-sm">
            {t("Book-quality courses with lessons, practice, and assessments — generated by AI", "বই-মানের কোর্স পাঠ, অনুশীলন এবং মূল্যায়ন সহ — AI দ্বারা তৈরি")}
          </p>
        </div>
        <HistoryDrawer
          config={{
            table: "generated_courses",
            titleField: "subject_name",
            pageTitle: t("Courses", "কোর্স"),
            icon: "📚",
            dateField: "updated_at",
            isPublic: true,
            formatSubtitle: (row: any) => `Class ${row.class_level} • ${row.language || "en"}`,
          }}
          onSelect={(item) => {
            if (item.chapters?.course_overview) {
              setCourse(item.chapters as unknown as CourseData);
            }
            setGeneratedTitle(item.subject_name);
          }}
        />
      </motion.div>

      {/* Prompt Input */}
      <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }}
        className="card-gradient border border-border rounded-xl p-5 space-y-4"
      >
        <div className="flex gap-2">
          <input
            type="text" value={prompt} onChange={(e) => setPrompt(e.target.value)}
            onKeyDown={(e) => e.key === "Enter" && !loading && handleGenerate()}
            placeholder={t("e.g. Teach me Python programming...", "যেমন: আমাকে Python প্রোগ্রামিং শেখাও...")}
            className="flex-1 px-4 py-3 rounded-lg bg-background border border-input text-foreground placeholder:text-muted-foreground focus:ring-2 focus:ring-ring outline-none text-sm"
          />
          <button onClick={handleGenerate} disabled={loading}
            className="px-5 py-3 rounded-lg bg-hero-gradient text-primary-foreground font-semibold hover:opacity-90 transition-opacity disabled:opacity-50 flex items-center gap-2"
          >
            {loading ? <Loader2 className="w-5 h-5 animate-spin" /> : <Send className="w-5 h-5" />}
          </button>
        </div>

        {!course && !loading && (
          <div>
            <p className="text-xs text-muted-foreground mb-2">{t("Try these:", "এগুলো চেষ্টা করো:")}</p>
            <div className="flex flex-wrap gap-2">
              {examplePrompts.map((ep, i) => (
                <button key={i} onClick={() => setPrompt(ep)}
                  className="text-xs px-3 py-1.5 rounded-full border border-border bg-background text-foreground hover:border-primary/50 transition-all"
                >
                  {ep}
                </button>
              ))}
            </div>
          </div>
        )}

        {loading && (
          <div className="flex flex-col items-center gap-2 py-8">
            <Loader2 className="w-8 h-8 animate-spin text-primary" />
            <p className="text-sm text-muted-foreground">
              {t("Designing your course structure...", "তোমার কোর্সের কাঠামো ডিজাইন করছে...")}
            </p>
            <p className="text-xs text-muted-foreground/70">
              {t("This creates a complete curriculum with modules, lessons & assessments", "মডিউল, পাঠ ও মূল্যায়ন সহ সম্পূর্ণ পাঠ্যক্রম তৈরি করছে")}
            </p>
          </div>
        )}
      </motion.div>

      {/* Course Viewer */}
      {course && (
        <CourseViewer
          course={course}
          courseName={generatedTitle}
          classLevel={profile?.class_level || "9"}
          onCourseUpdate={(updated) => setCourse(updated)}
        />
      )}
    </div>
  );
};

export default CoursesPage;
